package visao;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modeloBeans.BeansAlunos;
import modeloConection.ConexaoBD;
import modeloDao.ControleAlunos;

/**
 *
 * @author Cah
 */
public class CadastroAlunos extends javax.swing.JFrame {

    /*Buffer de imagem*/
    BufferedImage imagemBuffer = null;
    ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
    byte[] byteArray;

    ConexaoBD conex = new ConexaoBD();
    BeansAlunos mod = new BeansAlunos();
    ControleAlunos dao = new ControleAlunos();

    int flag = 0;

    public CadastroAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadastroProfessores = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblId_prof = new javax.swing.JLabel();
        txtCod_acesso = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSerie = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        ComboBoxAno = new javax.swing.JComboBox<>();
        lblFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCadastroProfessores.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTituloCadastroProfessores.setForeground(new java.awt.Color(153, 0, 0));
        lblTituloCadastroProfessores.setText("Cadastro de Alunos");
        getContentPane().add(lblTituloCadastroProfessores, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 16, 231, -1));

        btnNovo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 91, 40));

        btnSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 91, 40));

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 40));

        btnEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 91, 40));

        btnExcluir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 91, 40));

        lblId_prof.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblId_prof.setText("Cod. Acesso");
        getContentPane().add(lblId_prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        txtCod_acesso.setEnabled(false);
        txtCod_acesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_acessoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCod_acesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, 25));

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        txtNome.setEnabled(false);
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 25));

        lblSerie.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSerie.setText("Serie");
        getContentPane().add(lblSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        txtSerie.setEnabled(false);
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 70, 25));
        getContentPane().add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 216, 25));

        btnPesquisa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, 50));

        lblData.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblData.setText("Ano");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        btnVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 120, 40));

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sairSistema.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 73, 60));

        lblImagem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setText("Inserir Foto");
        lblImagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblImagem.setEnabled(false);
        lblImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagemMouseClicked(evt);
            }
        });
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, 110));

        ComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        ComboBoxAno.setEnabled(false);
        getContentPane().add(ComboBoxAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 70, 25));

        lblFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(lblFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        setSize(new java.awt.Dimension(593, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void getImagem() throws IOException {

        JFileChooser busca_foto = new JFileChooser();

        busca_foto.setFileFilter(new FileNameExtensionFilter("Imagem", "bmp", "png", "jpg", "jpeg"));
        busca_foto.setAcceptAllFileFilterUsed(false);

        busca_foto.setDialogTitle("Selecionar imagem");
        busca_foto.showOpenDialog(this);

        if (busca_foto.getSelectedFile() != null) {
            String caminho = "" + busca_foto.getSelectedFile().getAbsolutePath();
            imagemBuffer = ImageIO.read(new File(caminho));
            Image diminuirImagem = imagemBuffer.getScaledInstance(220, 100, 0);
            lblImagem.setText("");
            lblImagem.setIcon(new ImageIcon(diminuirImagem));
        }

    }

    public void SalvandoFoto() throws IOException {
        ImageIO.write(imagemBuffer, "jpeg",bytesImg);
        bytesImg.flush();
        byteArray = bytesImg.toByteArray();
        bytesImg.close();
        imagemBuffer = null;
        lblImagem.setIcon(null);
        

    }
    
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;

        //Liberar Caixa de texto
        lblImagem.setEnabled(true);
        txtNome.setEnabled(true);
        txtSerie.setEnabled(true);
        ComboBoxAno.setEnabled(true);

        //Liberar Botão
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(!true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (flag == 1) {
            try {
                SalvandoFoto();
                mod.setImagem(byteArray);
                mod.setNome(txtNome.getText());
                mod.setSerie(txtSerie.getText());
                mod.setAno_cadastro((String)ComboBoxAno.getSelectedItem());

                //Salvando os dados inseridos
                dao.Salvar(mod);

                //Limpando Campos após salvar
                txtCod_acesso.setText("");
                lblImagem.setIcon(null);
                lblImagem.setText("Inserir Foto");
                txtNome.setText("");
                txtSerie.setText("");
            } catch (IOException ex) {
                Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }

            //Bloqueando os campos novamente
            lblImagem.setEnabled(false);
            txtNome.setEnabled(false);
            txtSerie.setEnabled(false);
            ComboBoxAno.setEnabled(false);
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else {

            try {
                //Dados a ser alterados
                
                mod.setCod_acesso(Integer.parseInt(txtCod_acesso.getText()));
                SalvandoFoto();
                mod.setImagem(byteArray);
                mod.setNome(txtNome.getText());
                mod.setSerie(txtSerie.getText());
                mod.setAno_cadastro((String)ComboBoxAno.getSelectedItem());

                // Editar
                dao.EditarUser(mod);

                //Limpando Campos após salvar
                txtCod_acesso.setText("");
                lblImagem.setIcon(null);
                lblImagem.setText("Inserir a Foto");
                txtNome.setText("");
                txtSerie.setText("");
                txtPesquisa.setText("");

                //Bloqueando os campos novamente
                lblImagem.setEnabled(false);
                txtNome.setEnabled(false);
                txtSerie.setEnabled(false);
                ComboBoxAno.setEnabled(false);
                btnNovo.setEnabled(true);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);
            } catch (IOException ex) {
                Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Limpando Campos após Cancelar
        txtCod_acesso.setText("");
        lblImagem.setIcon(null);
        lblImagem.setText("Inserir a Foto");
        txtNome.setText("");
        txtSerie.setText("");
        txtPesquisa.setText("");

        //Bloquear campos
        lblImagem.setEnabled(!true);// (!) faz o oposto da instrução
        txtNome.setEnabled(!true);
        txtSerie.setEnabled(!true);
        ComboBoxAno.setEnabled(!true);

        btnCancelar.setEnabled(!true);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag = 2;
        //Liberando campos  
        lblImagem.setEnabled(true);
        txtNome.setEnabled(true);
        txtSerie.setEnabled(true);
        ComboBoxAno.setEnabled(true);

        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);

        //Bloqueando Botões
        btnEditar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCod_acesso(Integer.parseInt(txtCod_acesso.getText()));
            //  mod.setCodigo(Integer.parseInt(txtCodigo.getText()));
            dao.Excluir(mod);

            //Limpando Campos após excluir
            txtCod_acesso.setText("");
            lblImagem.setIcon(null);
            lblImagem.setText("Inserir a Foto");
            txtNome.setText("");
            txtSerie.setText("");
            txtPesquisa.setText("");
            txtPesquisa.setText("");

            //Bloqueando os campos novamente
            lblImagem.setEnabled(false);// 
            txtNome.setEnabled(false);
            txtSerie.setEnabled(false);
            ComboBoxAno.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
   
    public void getConsultar() throws IOException, SQLException, ClassNotFoundException {
        imagemBuffer = null;
        if (mod != null) {
            imagemBuffer = ImageIO.read(new ByteArrayInputStream(mod.getImagem()));
            Image diminuirImage = imagemBuffer.getScaledInstance(220, 100, 0);
            lblImagem.setText("");
            lblImagem.setIcon(new ImageIcon(diminuirImage));

        } else {
            JOptionPane.showMessageDialog(this, "Não existe cadastro");
        }

    }

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        mod.setPesquisa(txtPesquisa.getText());
        BeansAlunos model = dao.buscaAlunos(mod);
        try {

            txtCod_acesso.setText(String.valueOf(model.getCod_acesso()));// valueOf transforma valor em string
            getConsultar();
            txtNome.setText(model.getNome());
            txtSerie.setText(model.getSerie());
            ComboBoxAno.setSelectedItem(model.getAno_cadastro());
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnNovo.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(false);

        } catch (IOException ex) {
            Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            lblImagem.setIcon(null);
            lblImagem.setText("Inserir a Foto");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            lblImagem.setIcon(null);
            lblImagem.setText("Inserir a Foto");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            lblImagem.setIcon(null);
            lblImagem.setText("Inserir a Foto");
        }

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuProfessor menu = new MenuProfessor();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCod_acessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_acessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_acessoActionPerformed

    private void lblImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagemMouseClicked
        try {
            this.getImagem();
        } catch (IOException ex) {
            Logger.getLogger(CadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
            lblImagem.setIcon(null);
            lblImagem.setText("Inserir a Foto");
        }
    }//GEN-LAST:event_lblImagemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxAno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFundoTela;
    private javax.swing.JLabel lblId_prof;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTituloCadastroProfessores;
    private javax.swing.JTextField txtCod_acesso;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
