
package visao;

import javax.swing.JOptionPane;
import modeloBeans.BeansAdm;
import modeloConection.ConexaoBD;
import modeloDao.ControleAdm;


/**
 *
 * @author Cah
 */

public class CadastroAdm extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    BeansAdm mod = new BeansAdm();
    ControleAdm dao = new ControleAdm();
    int flag = 0;
  
    public CadastroAdm() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadastroProfessores = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblId_prof = new javax.swing.JLabel();
        txtId_adm = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblTituloCadastroProfessores.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTituloCadastroProfessores.setForeground(new java.awt.Color(153, 0, 0));
        lblTituloCadastroProfessores.setText("Cadastro de Administradores");
        getContentPane().add(lblTituloCadastroProfessores);
        lblTituloCadastroProfessores.setBounds(130, 22, 340, 34);

        btnNovo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo);
        btnNovo.setBounds(38, 88, 91, 40);

        btnSalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(38, 139, 91, 40);

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(38, 185, 91, 40);

        btnEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(38, 231, 91, 40);

        btnExcluir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(38, 277, 91, 40);

        lblId_prof.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblId_prof.setText("Identificação");
        getContentPane().add(lblId_prof);
        lblId_prof.setBounds(169, 101, 90, 21);

        txtId_adm.setEnabled(false);
        getContentPane().add(txtId_adm);
        txtId_adm.setBounds(269, 103, 201, 30);

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(170, 150, 90, 21);

        txtNome.setEnabled(false);
        getContentPane().add(txtNome);
        txtNome.setBounds(270, 140, 201, 30);

        lblUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(170, 190, 50, 21);

        txtUsuario.setEnabled(false);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(270, 180, 201, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 230, 41, 21);
        getContentPane().add(txtPesquisa);
        txtPesquisa.setBounds(166, 280, 210, 30);

        btnPesquisa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa);
        btnPesquisa.setBounds(380, 270, 95, 50);

        txtSenha.setEnabled(false);
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(270, 220, 127, 30);

        btnVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(360, 350, 110, 30);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sairSistema.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(500, 330, 60, 60);

        lblFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(lblFundoTela);
        lblFundoTela.setBounds(0, 0, 580, 400);

        setSize(new java.awt.Dimension(593, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        
        //Liberar Caixa de texto
        txtNome.setEnabled(true);
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
        
        //Liberar Botão
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);      
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(flag==1){
            //registrando dados inseridos.
            
            //mod.setId_adm(Integer.parseInt(txtId_adm.getText()));
            
            /* 
            Possivelmente o campo id_professor passará a ser o CPF, mas 
            enquanto estamos apenas testando deixaremos ele gerando no uma 
            numeração automaticapelo AI.
            */
            mod.setNome(txtNome.getText());
            mod.setUsuario(txtUsuario.getText());
            mod.setSenha(txtSenha.getText());

             //Salvando os dados inseridos
            dao.Salvar(mod);

            //Limpando Campos após salvar
            txtId_adm.setText("");
            txtNome.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");


            //Bloqueando os campos novamente
            txtNome.setEnabled(false);
            txtUsuario.setEnabled(false);
            txtSenha.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
        else{
            //Dados a ser alterados
            mod.setId_adm(Integer.parseInt(txtId_adm.getText()));
            mod.setNome(txtNome.getText());
            mod.setUsuario(txtUsuario.getText());
            mod.setSenha(txtSenha.getText());

            // Editar
            dao.EditarUser(mod);

            //Limpando Campos após salvar
            txtId_adm.setText("");
            txtNome.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtPesquisa.setText("");

            //Bloqueando os campos novamente
            txtNome.setEnabled(false);
            txtUsuario.setEnabled(false);
            txtSenha.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
      }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         //Limpando Campos após Cancelar
         txtId_adm.setText("");
         txtNome.setText("");
         txtUsuario.setText("");
         txtSenha.setText("");
         txtPesquisa.setText("");
       
        //Bloquear campos
        txtNome.setEnabled(!true);// (!) faz o oposto da instrução
        txtUsuario.setEnabled(!true);
        txtSenha.setEnabled(!true);
    
        btnCancelar.setEnabled(!true);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag=2;
        //Liberando campos  
        txtNome.setEnabled(true);
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
        
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        //Bloqueando Botões
        btnEditar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir?");
        if(resposta==JOptionPane.YES_OPTION){
            mod.setId_adm(Integer.parseInt(txtId_adm.getText()));
             //  mod.setCodigo(Integer.parseInt(txtCodigo.getText()));
            dao.Excluir(mod);
            
            //Limpando Campos após excluir
            txtId_adm.setText("");
            txtNome.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtPesquisa.setText("");
            txtPesquisa.setText("");

            //Bloqueando os campos novamente
            txtNome.setEnabled(false);// 
            txtUsuario.setEnabled(false);
            txtSenha.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
          mod.setPesquisa(txtPesquisa.getText());
        BeansAdm model = dao.buscaAdm(mod);
       
        txtId_adm.setText(String.valueOf(model.getId_adm()));// valueOf transforma valor em string
        txtNome.setText(model.getNome());
        txtUsuario.setText(model.getUsuario());
        txtSenha.setText(model.getSenha());;
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(false);
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuAdm menuadm = new MenuAdm();
        menuadm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
         String senha = txtSenha.getText();

        int quantCaracteres = senha.length();
        if (quantCaracteres > 7) {
            senha = senha.substring(0, senha.length() - 1);
            txtSenha.setText(senha);
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFundoTela;
    private javax.swing.JLabel lblId_prof;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTituloCadastroProfessores;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtId_adm;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}

