/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeloBeans.BeansContinhas;
import modeloConection.ConexaoBD;
import modeloDao.ControleContinhas;

/**
 *
 * @author Cah
 */
public final class JifContinhasDivisao extends javax.swing.JFrame {

    int tentativa = 0, ponto = 0, erro = 0;
    float num1 = 0, num2 = 0, resultado,divisao;
    ConexaoBD conex = new ConexaoBD();
    ControleContinhas dao = new ControleContinhas();
    BeansContinhas mod = new BeansContinhas();
  
    int flag = 0;

    public JifContinhasDivisao() {

        initComponents();
     //Aqui trago o numero do aluno com O System.getProperty() e apresento na jlId.
        String usuario = System.getProperty("login", "");
        jlId.setText(usuario);
        conex.conexao();
       conex.executaSql("select * from alunos where cod_acesso='"+ usuario +"'");
        try {
            conex.rs.first();
            jlNome.setText(conex.rs.getString("nome"));
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuAtividades.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconecta();
        jlResult.requestFocus();
        geradorNumerico();
        fazCalculo();
        // jlResultOculto.setText(String.valueOf(divisao));// mostra valor da divisao

    }

    public final void geradorNumerico() {
        Random random = new Random();
        num1 = random.nextInt(100);
        num2 = random.nextInt(100);
           if (num1 < num2) {
            jlNum1.setText(String.valueOf(num2));
            jlNum2.setText(String.valueOf(num1));

        } else {
            jlNum1.setText(String.valueOf(num1));
            jlNum2.setText(String.valueOf(num2));
        }
    }

    public void fazCalculo() {
        if (num1 < num2) {
            divisao = num2 - num1;
        
        }else{
            divisao = num1 - num2;
        }
    }

      public void contTentativas() {
        String usuario = System.getProperty("login", "");
        conex.conexao();
        conex.executaSql("select * from ranking2 where id_aluno='" + usuario + "'");

        tentativa = ponto + erro;
        if (tentativa > 10) {
            try {
                conex.rs.first();
                if (conex.rs.getString("id_aluno").equals(usuario)) {
                    mod.setId_aluno(Integer.parseInt(jlId.getText()));
                    mod.setPontos(Integer.parseInt(jlPontos.getText()));
                    // dao.Salvar(mod);
                    dao.EditarUser(mod);

                } else {
                   JOptionPane.showMessageDialog(null, " ERRO !", "Mensagem do Professor", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(JifContinhasAdicao.class.getName()).log(Level.SEVERE, null, ex);
            }
            conex.desconecta();
            JOptionPane.showMessageDialog(null, " ☻ FIM DA LIÇÃO !", "Mensagem do Professor", JOptionPane.INFORMATION_MESSAGE);
            MenuAtividades menu = new MenuAtividades();
            menu.setVisible(true);
            dispose();
        }
    }

    public void comparaResultado() {
        fazCalculo();
        if (divisao == resultado) {
            ponto++;
        } else {
            erro++;
        }
        contTentativas();
        limparCampo();

    }

    private void limparCampo() {
        jlResult.setText("");
        jlResult.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNum1 = new javax.swing.JLabel();
        jlSinal = new javax.swing.JLabel();
        jlNum2 = new javax.swing.JLabel();
        jlIgual = new javax.swing.JLabel();
        jlResult = new javax.swing.JTextField();
        jbAvancar = new javax.swing.JButton();
        jbApagar1 = new javax.swing.JButton();
        Pontos = new javax.swing.JLabel();
        jlPontos = new javax.swing.JLabel();
        jlErros = new javax.swing.JLabel();
        Erros = new javax.swing.JLabel();
        jlResultOculto = new javax.swing.JLabel();
        jlMensagem = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();
        jlFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONTINHA DE ÷");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNum1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNum1.setText("0");
        getContentPane().add(jlNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, 60));

        jlSinal.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlSinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSinal.setText("=");
        getContentPane().add(jlSinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 50, 50));

        jlNum2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNum2.setText("0");
        getContentPane().add(jlNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 100, 70));

        jlIgual.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIgual.setText("÷");
        getContentPane().add(jlIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, 50));

        jlResult.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlResultKeyPressed(evt);
            }
        });
        getContentPane().add(jlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 90, 70));

        jbAvancar.setBackground(new java.awt.Color(0, 204, 0));
        jbAvancar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbAvancar.setText("Próximo >>");
        jbAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 60));

        jbApagar1.setBackground(new java.awt.Color(204, 0, 0));
        jbApagar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbApagar1.setText("Apagar");
        jbApagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbApagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 130, 60));

        Pontos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Pontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pontos.setText("Pontos");
        getContentPane().add(Pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 90, 30));

        jlPontos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlPontos.setForeground(new java.awt.Color(0, 153, 0));
        jlPontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPontos.setText("0");
        getContentPane().add(jlPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, 30));

        jlErros.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlErros.setForeground(new java.awt.Color(204, 0, 0));
        jlErros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlErros.setText("0");
        getContentPane().add(jlErros, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 70, 30));

        Erros.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Erros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Erros.setText("Erros");
        getContentPane().add(Erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 80, 30));
        getContentPane().add(jlResultOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 20, -1));

        jlMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMensagem.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jlMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 370, 40));

        jlTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(153, 0, 0));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Continhas de Divisão");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 400, -1));

        jbVoltar.setBackground(new java.awt.Color(255, 255, 0));
        jbVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.setBorder(null);
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 100, 40));

        jlNome.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 350, 40));

        jlId.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(jlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jlFundoTela.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlFundoTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(jlFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1620, 940));

        setSize(new java.awt.Dimension(572, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlResultKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlResultKeyPressed

    }//GEN-LAST:event_jlResultKeyPressed

    private void jbAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAvancarActionPerformed

        fazCalculo();
        // jlResultOculto.setText(String.valueOf(soma));// mostra valor da soma
        resultado = Float.parseFloat(jlResult.getText());
        comparaResultado();
        geradorNumerico();
        jlPontos.setText(String.valueOf(ponto));
        jlErros.setText(String.valueOf(erro));
        //   jlMensagem.setText(String.valueOf(tentativa));// mostra quantidade de tentativas

    }//GEN-LAST:event_jbAvancarActionPerformed

    private void jbApagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagar1ActionPerformed
        limparCampo();
    }//GEN-LAST:event_jbApagar1ActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed

        MenuAtividades menu = new MenuAtividades();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JifContinhasDivisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JifContinhasDivisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JifContinhasDivisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JifContinhasDivisao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JifContinhasDivisao().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Erros;
    private javax.swing.JLabel Pontos;
    private javax.swing.JButton jbApagar1;
    private javax.swing.JButton jbAvancar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlErros;
    private javax.swing.JLabel jlFundoTela;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlIgual;
    private javax.swing.JLabel jlMensagem;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNum1;
    private javax.swing.JLabel jlNum2;
    private javax.swing.JLabel jlPontos;
    private javax.swing.JTextField jlResult;
    private javax.swing.JLabel jlResultOculto;
    private javax.swing.JLabel jlSinal;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
