/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cah
 */
public class JifQuebraCabeca extends javax.swing.JFrame {
    boolean t1,t2,t3,t4,t5,t6,t7,t8,t9;
   
    

    /**
     * Creates new form JifQuebraCabeca
     */
    public JifQuebraCabeca() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlQuebraCabeca = new javax.swing.JLabel();
        jlT1 = new javax.swing.JLabel();
        jlT9 = new javax.swing.JLabel();
        jlT5 = new javax.swing.JLabel();
        jlT8 = new javax.swing.JLabel();
        jlT2 = new javax.swing.JLabel();
        jlT4 = new javax.swing.JLabel();
        jlT6 = new javax.swing.JLabel();
        jlT3 = new javax.swing.JLabel();
        jlT7 = new javax.swing.JLabel();
        jlTR1 = new javax.swing.JLabel();
        jlTR2 = new javax.swing.JLabel();
        jlTR3 = new javax.swing.JLabel();
        jlTR4 = new javax.swing.JLabel();
        jlTR5 = new javax.swing.JLabel();
        jlTR6 = new javax.swing.JLabel();
        jlTR7 = new javax.swing.JLabel();
        jlTR8 = new javax.swing.JLabel();
        jlTR9 = new javax.swing.JLabel();
        jbProximo = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jlFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUEBRA - CABEÇA (DETONA RALPH)");
        setPreferredSize(new java.awt.Dimension(1275, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlQuebraCabeca.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jlQuebraCabeca.setForeground(new java.awt.Color(153, 0, 0));
        jlQuebraCabeca.setText("Detona Ralph");
        getContentPane().add(jlQuebraCabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jlT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T1.jpg"))); // NOI18N
        jlT1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT1MouseDragged(evt);
            }
        });
        getContentPane().add(jlT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, -1));

        jlT9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T9.jpg"))); // NOI18N
        jlT9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT9MouseDragged(evt);
            }
        });
        getContentPane().add(jlT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 200, -1));

        jlT5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T5.jpg"))); // NOI18N
        jlT5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT5MouseDragged(evt);
            }
        });
        getContentPane().add(jlT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, -1));

        jlT8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T8.jpg"))); // NOI18N
        jlT8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT8MouseDragged(evt);
            }
        });
        getContentPane().add(jlT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, -1));

        jlT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T2.jpg"))); // NOI18N
        jlT2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT2MouseDragged(evt);
            }
        });
        getContentPane().add(jlT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 200, 120));

        jlT4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T4.jpg"))); // NOI18N
        jlT4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT4MouseDragged(evt);
            }
        });
        getContentPane().add(jlT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 200, 120));

        jlT6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T6.jpg"))); // NOI18N
        jlT6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT6MouseDragged(evt);
            }
        });
        getContentPane().add(jlT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 200, 120));

        jlT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T3.jpg"))); // NOI18N
        jlT3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT3MouseDragged(evt);
            }
        });
        getContentPane().add(jlT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 120));

        jlT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlT7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/T7.jpg"))); // NOI18N
        jlT7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlT7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlT7MouseDragged(evt);
            }
        });
        getContentPane().add(jlT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, -1));

        jlTR1.setBackground(new java.awt.Color(255, 102, 0));
        jlTR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR1MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 200, 120));

        jlTR2.setBackground(new java.awt.Color(255, 102, 0));
        jlTR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR2MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 200, 120));

        jlTR3.setBackground(new java.awt.Color(255, 102, 0));
        jlTR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR3MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 200, 120));

        jlTR4.setBackground(new java.awt.Color(255, 102, 0));
        jlTR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR4MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 200, 120));

        jlTR5.setBackground(new java.awt.Color(255, 102, 0));
        jlTR5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR5MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 200, 120));

        jlTR6.setBackground(new java.awt.Color(255, 102, 0));
        jlTR6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR6MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, 200, 120));

        jlTR7.setBackground(new java.awt.Color(255, 102, 0));
        jlTR7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR7MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 200, 120));

        jlTR8.setBackground(new java.awt.Color(255, 102, 0));
        jlTR8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR8MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 200, 120));

        jlTR9.setBackground(new java.awt.Color(255, 102, 0));
        jlTR9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTR9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTR9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlTR9MouseEntered(evt);
            }
        });
        getContentPane().add(jlTR9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, 200, 120));

        jbProximo.setBackground(new java.awt.Color(0, 255, 51));
        jbProximo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbProximo.setText("Proximo >>");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });
        getContentPane().add(jbProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 220, 60));

        jbVoltar.setBackground(new java.awt.Color(255, 255, 0));
        jbVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.setBorder(null);
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 530, 120, 40));

        jlFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(jlFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 1270, 750));

        setSize(new java.awt.Dimension(1274, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlT1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT1MouseDragged
        jlT1.setLocation(jlT1.getX()+evt.getX(),jlT1.getY()+evt.getY());
        t1=true;
        
    }//GEN-LAST:event_jlT1MouseDragged

    private void jlT9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT9MouseDragged
        jlT9.setLocation(jlT9.getX()+evt.getX(),jlT9.getY()+evt.getY());
        t9=true;
        
    }//GEN-LAST:event_jlT9MouseDragged

    private void jlT5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT5MouseDragged
        jlT5.setLocation(jlT5.getX()+evt.getX(),jlT5.getY()+evt.getY());
        t5=true;
        
    }//GEN-LAST:event_jlT5MouseDragged

    private void jlT8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT8MouseDragged
        jlT8.setLocation(jlT8.getX()+evt.getX(),jlT8.getY()+evt.getY());
        t8=true;
        
    }//GEN-LAST:event_jlT8MouseDragged

    private void jlT2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT2MouseDragged
        jlT2.setLocation(jlT2.getX()+evt.getX(),jlT2.getY()+evt.getY());
        t2=true;
        
    }//GEN-LAST:event_jlT2MouseDragged

    private void jlT6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT6MouseDragged
        jlT6.setLocation(jlT6.getX()+evt.getX(),jlT6.getY()+evt.getY());
        t6=true;
        
    }//GEN-LAST:event_jlT6MouseDragged

    private void jlT4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT4MouseDragged
        jlT4.setLocation(jlT4.getX()+evt.getX(),jlT4.getY()+evt.getY());
        t4=true;
        
    }//GEN-LAST:event_jlT4MouseDragged

    private void jlT7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT7MouseDragged
        jlT7.setLocation(jlT7.getX()+evt.getX(),jlT7.getY()+evt.getY());
        t7=true;
        
    }//GEN-LAST:event_jlT7MouseDragged

    private void jlT3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlT3MouseDragged
        jlT3.setLocation(jlT3.getX()+evt.getX(),jlT3.getY()+evt.getY());
        t3=true;
        
    }//GEN-LAST:event_jlT3MouseDragged

    private void jlTR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR1MouseEntered
       if(t1){
           jlTR1.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T1.jpg"));
           jlT1.setVisible(false); 
       }
    }//GEN-LAST:event_jlTR1MouseEntered

    private void jlTR2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR2MouseEntered
        if(t2){
            jlTR2.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T2.jpg"));
            jlT2.setVisible(false); 
        }
    }//GEN-LAST:event_jlTR2MouseEntered

    private void jlTR3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR3MouseEntered
        if(t3){
            jlTR3.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T3.jpg"));
            jlT3.setVisible(false);
        }
  
    }//GEN-LAST:event_jlTR3MouseEntered

    private void jlTR4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR4MouseEntered
        if(t4){
            jlTR4.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T4.jpg"));
            jlT4.setVisible(false);
        }
    }//GEN-LAST:event_jlTR4MouseEntered

    private void jlTR5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR5MouseEntered
        if(t5){
            jlTR5.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T5.jpg"));
            jlT5.setVisible(false);
        }
    }//GEN-LAST:event_jlTR5MouseEntered

    private void jlTR6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR6MouseEntered
       if(t6){
           jlTR6.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T6.jpg"));
           jlT6.setVisible(false);
       }
    }//GEN-LAST:event_jlTR6MouseEntered

    private void jlTR7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR7MouseEntered
        if(t7){
            jlTR7.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T7.jpg"));
            jlT7.setVisible(false);
        }
    }//GEN-LAST:event_jlTR7MouseEntered

    private void jlTR8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR8MouseEntered
        if(t8){
            
            jlTR8.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T8.jpg"));
            jlT8.setVisible(false);
        }
    }//GEN-LAST:event_jlTR8MouseEntered

    private void jlTR9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTR9MouseEntered
        if(t9){
            jlTR9.setIcon(new ImageIcon("src/imagens/imagensQuebraCabeca/DetonaRaph/T9.jpg"));
            jlT9.setVisible(false);
        }
    }//GEN-LAST:event_jlTR9MouseEntered

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        MenuQuebraCabecas menuQB = new MenuQuebraCabecas();
        menuQB.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
        JifQuebraCabeca2 Qb2 = new JifQuebraCabeca2();
        Qb2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbProximoActionPerformed
    
    /*Quase Lá ;)*/
  /*  public void contTentativas() {
       
        if (encaixe ==9) {
            JOptionPane.showMessageDialog(null, " ☻ PARABENS !", "Mensagem do Professor", JOptionPane.INFORMATION_MESSAGE);
            MenuAtividades menu = new MenuAtividades();
            menu.setVisible(true);
            dispose();
            
        }
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JifQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JifQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JifQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JifQuebraCabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JifQuebraCabeca().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbProximo;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlFundoTela;
    private javax.swing.JLabel jlQuebraCabeca;
    private javax.swing.JLabel jlT1;
    private javax.swing.JLabel jlT2;
    private javax.swing.JLabel jlT3;
    private javax.swing.JLabel jlT4;
    private javax.swing.JLabel jlT5;
    private javax.swing.JLabel jlT6;
    private javax.swing.JLabel jlT7;
    private javax.swing.JLabel jlT8;
    private javax.swing.JLabel jlT9;
    private javax.swing.JLabel jlTR1;
    private javax.swing.JLabel jlTR2;
    private javax.swing.JLabel jlTR3;
    private javax.swing.JLabel jlTR4;
    private javax.swing.JLabel jlTR5;
    private javax.swing.JLabel jlTR6;
    private javax.swing.JLabel jlTR7;
    private javax.swing.JLabel jlTR8;
    private javax.swing.JLabel jlTR9;
    // End of variables declaration//GEN-END:variables
}
