/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import modeloConection.ConexaoBD;

/**
 *
 * @author Cah
 */
public class MenuContinhas extends JFrame {

    ConexaoBD conex = new ConexaoBD();

    /**
     * Creates new form MenuQuebraCabecas
     */
    public MenuContinhas() {
       initComponents();
       //Aqui trago o numero do aluno com O System.getProperty() e apresento na jlId.
        String usuario = System.getProperty("login", "");
        jlId.setText(usuario);
        conex.conexao();
       conex.executaSql("select * from alunos where cod_acesso='"+ usuario +"'");
        try {
            conex.rs.first();
            jlNome.setText(conex.rs.getString("nome"));
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuAtividades.class.getName()).log(Level.SEVERE, null, ex);
        }
        conex.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlQuebraCabeca = new javax.swing.JLabel();
        jbAdicao = new javax.swing.JButton();
        jlSubtracao = new javax.swing.JLabel();
        jlAdicao = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jbSubtracao = new javax.swing.JButton();
        jbMultiplicacao = new javax.swing.JButton();
        jlMultiplicacao = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlFundoTela = new javax.swing.JLabel();
        jbDivisao = new javax.swing.JButton();
        jlDivisao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU CONTINHAS");
        setMinimumSize(new java.awt.Dimension(515, 516));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlQuebraCabeca.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jlQuebraCabeca.setForeground(new java.awt.Color(153, 0, 0));
        jlQuebraCabeca.setText("Continhas");
        getContentPane().add(jlQuebraCabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jbAdicao.setBackground(new java.awt.Color(255, 255, 255));
        jbAdicao.setFont(new java.awt.Font("Comic Sans MS", 1, 75)); // NOI18N
        jbAdicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Adicao.png"))); // NOI18N
        jbAdicao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbAdicao.setBorderPainted(false);
        jbAdicao.setContentAreaFilled(false);
        jbAdicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 100, 80));

        jlSubtracao.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlSubtracao.setText("Subtração");
        getContentPane().add(jlSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 20));

        jlAdicao.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlAdicao.setText("Adição");
        getContentPane().add(jlAdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        jbVoltar.setBackground(new java.awt.Color(255, 255, 0));
        jbVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jbSubtracao.setBackground(new java.awt.Color(255, 255, 255));
        jbSubtracao.setFont(new java.awt.Font("Comic Sans MS", 1, 75)); // NOI18N
        jbSubtracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Subtracao.png"))); // NOI18N
        jbSubtracao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbSubtracao.setBorderPainted(false);
        jbSubtracao.setContentAreaFilled(false);
        jbSubtracao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbSubtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, 80));

        jbMultiplicacao.setBackground(new java.awt.Color(255, 255, 255));
        jbMultiplicacao.setFont(new java.awt.Font("Comic Sans MS", 1, 75)); // NOI18N
        jbMultiplicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Multiplicacao.png"))); // NOI18N
        jbMultiplicacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbMultiplicacao.setBorderPainted(false);
        jbMultiplicacao.setContentAreaFilled(false);
        jbMultiplicacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 100, 80));

        jlMultiplicacao.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlMultiplicacao.setText("Multiplicação");
        getContentPane().add(jlMultiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 20));

        jlId.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        jlNome.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 340, 30));

        jlFundoTela.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlFundoTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(jlFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -410, 1660, 950));

        jbDivisao.setBackground(new java.awt.Color(255, 255, 255));
        jbDivisao.setFont(new java.awt.Font("Comic Sans MS", 1, 75)); // NOI18N
        jbDivisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Divisao.png"))); // NOI18N
        jbDivisao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbDivisao.setBorderPainted(false);
        jbDivisao.setContentAreaFilled(false);
        jbDivisao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivisaoActionPerformed(evt);
            }
        });
        getContentPane().add(jbDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, 80));

        jlDivisao.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlDivisao.setText("Divisão");
        getContentPane().add(jlDivisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, 20));

        setSize(new java.awt.Dimension(534, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void AlunoLogado() {

        try {

            conex.rs.first();

            jlNome.setText(conex.rs.getString("nome"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados!/n" + ex);
        }
    }
    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        MenuAtividades menu = new MenuAtividades();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbAdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicaoActionPerformed
        JifContinhasAdicao add = new JifContinhasAdicao();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbAdicaoActionPerformed

    private void jbSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtracaoActionPerformed
        JifContinhasSubtracao sub = new JifContinhasSubtracao();
        sub.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbSubtracaoActionPerformed

    private void jbDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivisaoActionPerformed
        JifContinhasDivisao divisao = new JifContinhasDivisao();
        divisao.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbDivisaoActionPerformed

    private void jbMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicacaoActionPerformed
        JifContinhasMultiplicacao mult = new JifContinhasMultiplicacao();
        mult.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbMultiplicacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuContinhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuContinhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuContinhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuContinhas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuContinhas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdicao;
    private javax.swing.JButton jbDivisao;
    private javax.swing.JButton jbMultiplicacao;
    private javax.swing.JButton jbSubtracao;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlAdicao;
    private javax.swing.JLabel jlDivisao;
    private javax.swing.JLabel jlFundoTela;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlMultiplicacao;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQuebraCabeca;
    private javax.swing.JLabel jlSubtracao;
    // End of variables declaration//GEN-END:variables

    void recebendo(String recebe) {
        jlId.setText(recebe);
    }
}
