/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Cah
 */
public class MenuQuebraCabecas extends javax.swing.JFrame {

    /**
     * Creates new form MenuQuebraCabecas
     */
    public MenuQuebraCabecas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlQuebraCabeca = new javax.swing.JLabel();
        jbQC1 = new javax.swing.JButton();
        jbQC2 = new javax.swing.JButton();
        jlViva = new javax.swing.JLabel();
        jlDR1 = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        jlFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUEBRA CABEÇAS");
        setMinimumSize(new java.awt.Dimension(730, 460));
        setPreferredSize(new java.awt.Dimension(720, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlQuebraCabeca.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jlQuebraCabeca.setForeground(new java.awt.Color(153, 0, 0));
        jlQuebraCabeca.setText("Quebra Cabeças");
        getContentPane().add(jlQuebraCabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jbQC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/DetonaRaph/DetonaRalph.jpg"))); // NOI18N
        jbQC1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbQC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQC1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbQC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 290, 170));

        jbQC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagensQuebraCabeca/Viva/Viva.jpg"))); // NOI18N
        jbQC2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbQC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQC2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbQC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 290, 170));

        jlViva.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlViva.setText("Viva - A vida é uma festa");
        getContentPane().add(jlViva, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, 20));

        jlDR1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlDR1.setText("Detona Ralph");
        getContentPane().add(jlDR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        jbVoltar.setBackground(new java.awt.Color(255, 255, 0));
        jbVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jlFundoTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(jlFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -290, 1390, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        MenuAtividades menu = new MenuAtividades();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbQC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQC1ActionPerformed
        JifQuebraCabeca Qb1 = new JifQuebraCabeca();
        Qb1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbQC1ActionPerformed

    private void jbQC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQC2ActionPerformed
        JifQuebraCabeca2 Qb2 = new JifQuebraCabeca2();
        Qb2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbQC2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuQuebraCabecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuQuebraCabecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuQuebraCabecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuQuebraCabecas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuQuebraCabecas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbQC1;
    private javax.swing.JButton jbQC2;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlDR1;
    private javax.swing.JLabel jlFundoTela;
    private javax.swing.JLabel jlQuebraCabeca;
    private javax.swing.JLabel jlViva;
    // End of variables declaration//GEN-END:variables
}
