/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansContinhas;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDao.ControleContinhas;

/**
 *
 * @author Cah
 */
public class RankingAlunos extends javax.swing.JFrame {

    BeansContinhas mod = new BeansContinhas();
    ControleContinhas control = new ControleContinhas();
     ConexaoBD conex = new ConexaoBD();
   

    /**
     * Creates new form RankingAlunos
     */
    
    public RankingAlunos() {
        initComponents();
        preencherTabela("SELECT id_aluno,nome,pontos from ranking2 as R "
                + "INNER JOIN alunos as A ON R.id_aluno = A.cod_acesso "
                + "GROUP BY id_aluno ORDER BY pontos DESC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtPontos = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        bntVoltar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar1 = new javax.swing.JButton();
        lblFundoTela = new javax.swing.JLabel();
        lblIdAluno = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RANKING DOS ALUNOS");
        getContentPane().setLayout(null);

        txtNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNome);
        txtNome.setBounds(180, 120, 200, 27);

        txtPontos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtPontos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPontos.setEnabled(false);
        getContentPane().add(txtPontos);
        txtPontos.setBounds(180, 150, 100, 27);

        btnPesquisar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(390, 120, 100, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName(""); // NOI18N
        jTable1.setPreferredSize(new java.awt.Dimension(350, 64));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 200, 340, 150);

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNome.setText("Id Aluno");
        getContentPane().add(lblNome);
        lblNome.setBounds(80, 120, 90, 21);

        lblPontos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPontos.setText("Pontos");
        getContentPane().add(lblPontos);
        lblPontos.setBounds(80, 150, 60, 21);

        lblRanking.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblRanking.setForeground(new java.awt.Color(153, 0, 0));
        lblRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRanking.setText("Ranking dos Alunos");
        getContentPane().add(lblRanking);
        lblRanking.setBounds(190, 20, 250, 40);

        bntVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        bntVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        bntVoltar.setText("Voltar");
        bntVoltar.setBorder(null);
        bntVoltar.setBorderPainted(false);
        bntVoltar.setContentAreaFilled(false);
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bntVoltar);
        bntVoltar.setBounds(380, 420, 90, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sairSistema.png"))); // NOI18N
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(500, 410, 60, 60);

        btnPesquisar1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnPesquisar1.setText("Nova Pesquisa");
        btnPesquisar1.setToolTipText("");
        btnPesquisar1.setEnabled(false);
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar1);
        btnPesquisar1.setBounds(370, 160, 140, 30);

        lblFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        lblFundoTela.setText("jLabel1");
        getContentPane().add(lblFundoTela);
        lblFundoTela.setBounds(-10, 0, 1941, 1071);

        lblIdAluno.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblIdAluno.setText("Id");
        getContentPane().add(lblIdAluno);
        lblIdAluno.setBounds(120, 80, 30, 21);

        txtIdAluno.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtIdAluno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdAluno.setEnabled(false);
        txtIdAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdAluno);
        txtIdAluno.setBounds(180, 90, 60, 27);

        setSize(new java.awt.Dimension(603, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        mod.setPesquisa(txtNome.getText());
        BeansContinhas model = control.buscaResultado(mod);
        txtIdAluno.setText(String.valueOf(model.getId()));// valueOf transforma valor em string
        txtNome.setText(String.valueOf(model.getId_aluno()));
        txtPontos.setText(String.valueOf(model.getPontos()));

        btnPesquisar.setEnabled(!true);
        txtNome.setEnabled(!true);
        btnPesquisar1.setEnabled(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed
        txtIdAluno.setText("");
        txtNome.setText("");
        txtPontos.setText("");
        
        btnPesquisar.setEnabled(true);
        lblNome.setText("Cod Acesso");
        txtNome.setEnabled(true);
        btnPesquisar1.setEnabled(!true);

    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void txtIdAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAlunoActionPerformed

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
       MenuProfessor menu = new MenuProfessor();
       menu.setVisible(true);
       dispose();
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String aluno = "" + jTable1.getValueAt(jTable1.getSelectedRow(),0);
        conex.conexao();
        conex.executaSql("SELECT id, id_aluno,nome,pontos from ranking2 as R "
                + "INNER JOIN alunos as A ON R.id_aluno = A.cod_acesso where id_aluno= '" + aluno + "'");
        
         try {
       conex.rs.first();
        txtIdAluno.setText(String.valueOf(conex.rs.getInt("id")));
        txtNome.setText(conex.rs.getString("nome"));
        txtPontos.setText(String.valueOf(conex.rs.getInt("pontos")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar os dados!/n"+ex);
        }
        conex.desconecta();
        btnPesquisar.setEnabled(!true);
        btnPesquisar1.setEnabled(true); 
        lblNome.setText("Nome");
    }//GEN-LAST:event_jTable1MouseClicked


    public void preencherTabela(String Sql) {

        ArrayList dados = new ArrayList();
        String[] item = new String[]{"COD. ACESSO", "ALUNO", "PONTOS"};

        conex.conexao();
        conex.executaSql(Sql);

        try {

            conex.rs.first();// Seta o primeiro registro da pesquisa
            do { //Add linhas

                dados.add(new Object[]{conex.rs.getInt("id_aluno"), conex.rs.getString("nome"), conex.rs.getInt("pontos")});
            } while (conex.rs.next());// Enquanto houver dados ele vai percorrer os registros

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList" + ex);
        }

        ModeloTabela modelo = new ModeloTabela(dados,item);

        jTable1.setModel(modelo);
        //id_aluno
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);//Tamanho da tabela
        jTable1.getColumnModel().getColumn(0).setResizable(false);//Define se o usuario poder redimencionar a tabela "nesse caso não pode"
        //nome
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        //Pontos
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);// Não permite que seja reordenar o cabeçalho
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);//Não permite redimencionar a tabela
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);// Permite selecionar apenas uma linha dado por vez

        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFundoTela;
    private javax.swing.JLabel lblIdAluno;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPontos;
    // End of variables declaration//GEN-END:variables
}
