/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author orteca
 */
public class TelaOpAdministrativas extends javax.swing.JFrame {

    /**
     * Creates new form TelaOpAdministrativas
     */
    public TelaOpAdministrativas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfessor = new javax.swing.JButton();
        btnAdm = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblObservacoes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblProfessores = new javax.swing.JLabel();
        lblAdm = new javax.swing.JLabel();
        lblFundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN ADMINISTRATIVO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProfessor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/professores.png"))); // NOI18N
        btnProfessor.setBorder(null);
        btnProfessor.setBorderPainted(false);
        btnProfessor.setContentAreaFilled(false);
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 90));

        btnAdm.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Administrador.png"))); // NOI18N
        btnAdm.setToolTipText("");
        btnAdm.setBorder(null);
        btnAdm.setBorderPainted(false);
        btnAdm.setContentAreaFilled(false);
        btnAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, 90));

        btnVoltar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sairSistema.png"))); // NOI18N
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, -1));

        lblObservacoes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblObservacoes.setText("*Realize o login de acordo com seu tipo de usuário.");
        getContentPane().add(lblObservacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Opções administrativas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblProfessores.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblProfessores.setText("Professores");
        getContentPane().add(lblProfessores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        lblAdm.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblAdm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdm.setText("Administradores");
        getContentPane().add(lblAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        lblFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundodetela.jpg"))); // NOI18N
        getContentPane().add(lblFundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        setSize(new java.awt.Dimension(486, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        LoginProfessor prof = new LoginProfessor();
        prof.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmActionPerformed
        LoginAdm adm = new LoginAdm();
        adm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdmActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOpAdministrativas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdm;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAdm;
    private javax.swing.JLabel lblFundoTela;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblProfessores;
    // End of variables declaration//GEN-END:variables
}
